import Navbar from './Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import Unlocked from '@/components/home/Unlocked/Unlocked';
import FeedbackItem from '@/components/home/FeedbackItem/FeedbackItem';
import Input from '@/components/UI/Input/Input';
import Companies from "@/components/home/Companies/Companies";
import Nextgen from "@/components/home/Nextgen/Nextgen";
import CRM from "@/components/home/CRM/CRM";
export { Navbar,Footer,Unlocked,FeedbackItem,Input,Companies,Nextgen,CRM };